version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: "Dockerfile.nginx"
    container_name: test_nginx
    ports:
      - 80:80
      - 443:443

  db:
    image: postgres:15
    container_name: test_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  test:
    image: test_image
    build:
      context: .
    container_name: test_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
#    command:
#      ["/test/docker/app.sh"]
    command: sh -c "alembic upgrade head && gunicorn myApp.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
#    ports:
#      - 9000:8000

volumes:
  postgresdata: